os: Visual Studio 2019
platform: Any CPU
skip_branch_with_pr: true
configuration: Release
install:
    - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
before_build:
    - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
    - ps: Vsix-TokenReplacement Conan.VisualStudio\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'
    - nuget restore
build_script:
    - msbuild /p:DeployExtension=false /p:verbosity=detailed
    - ps: .\vsix\sign.ps1
artifacts:
    - path: Conan.VisualStudio\bin\Release\Conan.VisualStudio.vsix
      name: Conan Visual Studio Extention
deploy:
    - provider: GitHub
      tag: v$(appveyor_build_version)
      release: Conan Visual Studio Extention v$(appveyor_build_version)
      description: Conan Visual Studio Extention v$(appveyor_build_version)
      auth_token:
        secure: 2Eh4YpQsYERkDVSLjyc0iWEmCZ0VIa4iFxqOmcgsgr44x6Q6w8cYOzDaURRUFp30
      draft: true
      prerelease: true
      force_update: false
      on:
        branch: publish-to-github  # https://www.appveyor.com/docs/deployment/github/
deploy_script:
    - ps: |
        if ($env:APPVEYOR_REPO_BRANCH -ne "master") { return }
        if (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) { return }
        .\vsix\sign.ps1
        .\vsix\publish.ps1
        Vsix-PublishToGallery
